name: Download and Commit Latest Stockfish Dev

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Запуск ежедневно в 03:00 UTC

jobs:
  download_and_commit_stockfish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Установить jq
        uses: dcarbone/install-jq-action@v3
        with:
          version: '1.8.1'

      - name: Запросить URL последнего релиза Stockfish
        id: get_url
        run: |
          url=$(curl -s https://api.github.com/repos/official-stockfish/Stockfish/releases \
            | jq -r '[.[] | select(.prerelease == true and (.tag_name | test("^stockfish-dev")))] | .[0].assets[] | select(.name | test("stockfish-ubuntu-x86-64.*tar$")).browser_download_url')
          if [ -z "$url" ]; then
            echo "Не удалось найти URL для скачивания. Выход из скрипта."
            exit 1
          fi
          echo "ASSET_URL=$url" >> $GITHUB_ENV

      - name: Скачать и распаковать Stockfish
        run: |
          curl -L "$ASSET_URL" -o stockfish.tar
          tar -xf stockfish.tar

      - name: Переместить и переименовать бинарник Stockfish в 'engines/stockfish'
        run: |
          mkdir -p engines
          mv stockfish*/stockfish engines/stockfish
          chmod +x engines/stockfish

      - name: Очистить временные файлы
        run: rm -rf stockfish stockfish.tar

      - name: Закоммитить и запушить изменения
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add engines/stockfish
          git diff --cached --quiet || (git commit -m "Обновить бинарник Stockfish до последней dev-версии" && git push)
